### ISSUE TITLE
Pretrained model seems broken

### ISSUE THREAD

**Issue by yzhang93** [asingh33/CNNGestureRecognizer#10]
Hi @asingh33,

This is a very impressive work! I'd like to try the demo, but it seems that the hdf5 file is broken in someway. I've only got a 35.06K file after download it from the github.

Is it possible for you to provide a new version? Thanks a lot.

**Comment by asingh33** [comment]
Thanks. You will require gitlfs tool to download this lfs file type.
But if you still get issue to download then you can use my google drive link instead of download - https://drive.google.com/open?id=0B6cMRAuImU69SHNCcXpkT3RpYkE

**Comment by yzhang93** [comment]
Thanks for your help!

**Comment by asingh33** [comment]
Sure no problem. Closing this issue now.
