### ISSUE TITLE
cant open file name="bw_4015imgs_weights.hdf5"

### ISSUE THREAD

**Issue by yam0927** [asingh33/CNNGestureRecognizer#11]
I load your ori_4015xxx.hdf5 file successfully,but i failed to open another file(bw_4015imgs_weights.hdf5).
When i run your code ,press 3 to visualize and then press 1,an error occured:Unable to open file:name=‘bw_4015imgs_weights.hdf5’,errno=2,error message='no such file or directory'

I also cant find this file in your code,
How can i do to solve this problem?

**Comment by asingh33** [comment]
Hey Yam,
That file is not needed actually. That was some old test training I did while working on the project. The ori_4015xxx.hdf5 is sufficient or you can create one as well for all other operations in the script.

**Comment by yam0927** [comment]
wow,i see,thanks a lot~
