### ISSUE TITLE
IOError: Unable to open file (File signature not found)

### ISSUE THREAD

**Issue by adaxidedakaonang** [asingh33/CNNGestureRecognizer#12]
Excuse me sir,when I choose 1 to use pretrained model, I meet this problem:

loading  ori_4015imgs_weights.hdf5
Traceback (most recent call last):
  File "trackgesture.py", line 299, in <module>
    Main()
  File "trackgesture.py", line 175, in Main
    mod = myNN.loadCNN(0)
  File "/Users/Arduino/Downloads/CNNGestureRecognizer-master/gestureCNN.py", line 174, in loadCNN
    model.load_weights(fname)
  File "/Users/Arduino/tensosflow/lib/python2.7/site-packages/keras/models.py", line 721, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/Arduino/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (File signature not found)

Im sorry that Im not really know what the problem is, my mac is cpu only, so I dont train model by myself. Do you know how to solve it? Please tell me. Thanks!!!

**Comment by adaxidedakaonang** [comment]
Now Im training model by your sample, Its OK. After finish training, I will tell you again.

Train on 2569 samples, validate on 643 samples
Epoch 1/15
2569/2569 [==============================] - 1082s 421ms/step - loss: 1.9586 - acc: 0.2067 - val_loss: 1.6045 - val_acc: 0.2068
Epoch 2/15
2569/2569 [==============================] - 1285s 500ms/step - loss: 1.5979 - acc: 0.2308 - val_loss: 1.6178 - val_acc: 0.2068
Epoch 3/15
2569/2569 [==============================] - 1289s 502ms/step - loss: 1.5770 - acc: 0.2814 - val_loss: 1.5692 - val_acc: 0.2908
Epoch 4/15
2569/2569 [==============================] - 1273s 496ms/step - loss: 1.4796 - acc: 0.3624 - val_loss: 1.4909 - val_acc: 0.3390
Epoch 5/15
2569/2569 [==============================] - 1305s 508ms/step - loss: 1.2344 - acc: 0.5021 - val_loss: 1.4858 - val_acc: 0.3857
Epoch 6/15
2569/2569 [==============================] - 1264s 492ms/step - loss: 0.9851 - acc: 0.6189 - val_loss: 1.5167 - val_acc: 0.4292
Epoch 7/15
2569/2569 [==============================] - 1314s 512ms/step - loss: 0.8039 - acc: 0.6960 - val_loss: 1.5183 - val_acc: 0.4308
Epoch 8/15
2569/2569 [==============================] - 1465s 570ms/step - loss: 0.6512 - acc: 0.7509 - val_loss: 1.6991 - val_acc: 0.4246
Epoch 9/15
2569/2569 [==============================] - 1387s 540ms/step - loss: 0.5568 - acc: 0.7945 - val_loss: 1.8646 - val_acc: 0.4401
Epoch 10/15
2569/2569 [==============================] - 1384s 539ms/step - loss: 0.4873 - acc: 0.8159 - val_loss: 1.8739 - val_acc: 0.4339
Epoch 11/15
2569/2569 [==============================] - 2164s 842ms/step - loss: 0.4566 - acc: 0.8233 - val_loss: 1.9344 - val_acc: 0.4572
Epoch 12/15
2560/2569 [============================>.] - ETA: 8s - loss: 0.3950 - acc: 0.8441

**Comment by adaxidedakaonang** [comment]
Hey, after finish training my model, I meet this issue again, I guess the problem may be your file rather than python? Hope your answer:)Thanks.

**Comment by adaxidedakaonang** [comment]
I think I find the problem, the file:ori_4015imgs_weights.hdf5 is wrong? I use my model file and rename it with ori_4015imgs_weights.hdf5, the process works good. Thanks your code, it's cool:)

**Comment by adaxidedakaonang** [comment]
Hey, I download the new .hdf5 from your google driver, it's ok, I suggest that may be you can replace your .hdf5 file with that in your driver. Good luck! Good day!

**Comment by aadarshpratik1** [comment]
Hey.... I'm running into the exact same error but didn't really understand how to fix it by reading your comments.... Can u help me out a bit....

**Comment by adaxidedakaonang** [comment]
For me ,I just download the .hdf5 file at there https://drive.google.com/open?id=0B6cMRAuImU69SHNCcXpkT3RpYkE, and this works well. you can try to download this file to replace the same one which in the above content.
