### ISSUE TITLE
Two kinds of images and hwo to speed the app up?

### ISSUE THREAD

**Issue by Ethanwl** [asingh33/CNNGestureRecognizer#17]
You use two kinds of images, binary and skinMask. Would this method reduce accuracy? If I train the model with skinMask, and then use the model to predict skinMask only, would it be better?
I run the app on my laptop with i5-5200U CPU，however，it couldn't run smoothly when predicting. Without GPU, is there any other way to speed the app up?

**Comment by asingh33** [comment]
@Ethanwl  I have some perf tweaking to the existing project, basically added multithreaded execution of CNN prediction callbacks. So now you should see literally no perf drop when prediction mode is on. So did some more perf tweaking regarding how many times per frame to call into CNN for gesture prediction.
So let me know if this helps.

**Comment by asingh33** [comment]
@Ethanwl  
I am closing this issue. Hope you are fine. My last commits should have improved the overall performance while predicting.
