### ISSUE TITLE
How can liveplot.py  show the result of gesture-recognition?

### ISSUE THREAD

**Issue by trywhencan** [asingh33/CNNGestureRecognizer#18]
The figure don not change whan I run liveplot.py and select Prediction mode. What should I do to let it work? Could you help me?

**Comment by trywhencan** [comment]
After I change the mode to CNN mode, I solve it. It seems that the binary mode can not achieve gesture-recognition and the date of out file in binary mode change only little. Why is that?

**Comment by drzraf** [comment]
same here.
Whether KERAS_BACKEND is set to theano or not, gesture == `NOTHING` (with a certainity between 90% and 99%).
`$ md5sum ori_4015imgs_weights.hdf5`
87a4e72d9a72995ebd37364595ba5e89

**Comment by asingh33** [comment]
Yeah thats weird. May I know which platform OS are you running on ?

**Comment by asingh33** [comment]
Just FYI,  I have just updated the project to show the predicted gesture probability graph. So no more need to run that liveplot.py script.
