### ISSUE TITLE
sorry. I always get the problem "IOError: Unable to open file (File signature not found)",file is "ori_4015imgs_weights.hdf5".

### ISSUE THREAD

**Issue by bingchenqin** [asingh33/CNNGestureRecognizer#21]

**Comment by bingchenqin** [comment]
batch response: This repository is over its data quota. Purchase more data packs to restore access.

when I use git lfs push.get this prioblem.

**Comment by As3O4** [comment]
Did you solve this problem?
I get the same problem.
So sad.

**Comment by asingh33** [comment]
Guys please use the alternative source to download the hdf5 file - https://drive.google.com/open?id=0B6cMRAuImU69SHNCcXpkT3RpYkE

ori_4015imgs_weights.hdf5 : This is pretrained file. If for some reason you find issues with downloading from github then it can be downloaded from my google driver link - https://drive.google.com/open?id=0B6cMRAuImU69SHNCcXpkT3RpYkE
