### ISSUE TITLE
line 295 of gestureCNN.py is wrong cause by numpy's version

### ISSUE THREAD

**Issue by yuriFish** [asingh33/CNNGestureRecognizer#30]
I got an error at gestureCNN.py in line 295. This may cause by my numpy's version which is 1.14.2. I change the code from "total_images / nb_classes" to "total_images // nb_classes", and then the code is working fine. 
File "gestureCNN.py", line 299, in initializers  label[s:r] = classIndex
TypeError: slice indices must be integers or None or have an __index__ method
My English is not very good and I hope u can understand it. BTW this demo is very good and help me a lot.

**Comment by asingh33** [comment]
Hey,

I think that might not be the right solution.
Instead can you try with this:

line#300, make those s & r as integer and check.
label[**int(s):int(r)**] = classIndex
