### ISSUE TITLE
OSError: cannot identify image file './imgfolder_b/Thumbs.db'

### ISSUE THREAD

**Issue by kaimonhtun** [asingh33/CNNGestureRecognizer#36]
Excuse me sir!I have an issue about immatrix in def initializers() while running.Please help me about that problem
![screenshot 84](https://user-images.githubusercontent.com/47453776/52485961-6b0e0a00-2be8-11e9-881e-fb1253248f9c.png)

**Comment by asingh33** [comment]
Can you please elaborate more like 
what option you were trying when this issue happened?

**Comment by asingh33** [comment]
Closing this issue, as no further update from the filer.
