### ISSUE TITLE
didn't you detect hand?

### ISSUE THREAD

**Issue by tianyu06030020** [asingh33/CNNGestureRecognizer#4]
I haven't run your code, but as your demo shows, I have a question,
do you detect hand?  because I see the hand bounding box is solid, I 
guess your work is just gesture recognition and not hand detect, is that?

**Comment by asingh33** [comment]
Yes thats right. I wanted to keep it simple so didnt add hand detection code.

**Comment by asingh33** [comment]
I am closing this issue.
