### ISSUE TITLE
Always detecting PUNCH

### ISSUE THREAD

**Issue by sanjanasri** [asingh33/CNNGestureRecognizer#46]
HI,

  First I congratulate you for your wonderful work. I tried to predict gestures with retrained weights, but I always get PUNCH as predicted output. Along with it, i get few errors too. I am attaching the screenshot for your reference. it would be great if i could get an earliest response
![gesture](https://user-images.githubusercontent.com/13214774/62193289-15dfd380-b395-11e9-9dcd-cadd3859013d.png)

**Comment by asingh33** [comment]
Just retrain the model for Linux.
I have recently found a new observation that same pretrained weight file doesnt work across the platform. The default weight files I had earlier provided with the repo was on Windows. So it wont work as it is for macOS or Linux.
Today I have provided links to two macOS and Windows specific weight files. 
Pull the latest code and try these weight file or retrain. It will work.
