### ISSUE TITLE
Error with importing tensorflow after running trackgesture.py 

### ISSUE THREAD

**Issue by superuser992002** [asingh33/CNNGestureRecognizer#47]
Here is my console when i run trackgesture on visual studio with anaconda (have tensorflow 1.13.1)
![image](https://user-images.githubusercontent.com/51882888/62824273-a2746800-bbc5-11e9-9012-7c8c829081c4.png)

**Comment by asingh33** [comment]
I haven't used Visual Studio for python. Not sure if you found the solution to your issue, but if you have then it would be good if you post it here. It would be good to know info for others.

**Comment by asingh33** [comment]
I am closing this issue. Basically you need to have tensorflow module installed. Let me know if you still face issue after installing tensorflow package.

**Comment by superuser992002** [comment]
I have solved it, it is exactly that keras has malfunction with interacting
python 3.7 so i downgraded it and it works. thank you for spending time

Vào 18:40, Th 3, 19 thg 11, 2019 Abhishek Singh <notifications@github.com>
đã viết:
