### ISSUE TITLE
cannot get model weights ori_4015imgs_weights.hdf5

### ISSUE THREAD

**Issue by JarveeLee** [asingh33/CNNGestureRecognizer#5]
Dear author,

I count not get the weights ori_4015imgs_weights.hdf5 through the website in this 4015imgs_weights.hdf5. Could you please update a new website.

Thanks for help.

Best regards,
Anran Qi

**Comment by asingh33** [comment]
@JarveeLee 
Sorry about that. I believe my GIT LFS quota has crossed its bandwidth limit. Github has disabled GIT LFS for the rest of month 👎. I will purchase an upgrade package to unlock it.

**Comment by MengXinChengXuYuan** [comment]
@JarveeLee
Hi
I got the same problem
Whatever I tried, I can just get a hdf5 file of 134 bytes
But it should be 150Mb right?

**Comment by asingh33** [comment]
Ok done, I got it increased. Try pulling now.

**Comment by asingh33** [comment]
@JarveeLee @MengXinChengXuYuan  Please let me know if you can download the weight file now and I can close this issue.

**Comment by sumit26696** [comment]
do you have to constantly upgrade it? because its 134 bytes again and giving me the same error
