### ISSUE TITLE
TypeError: Indexing elements must be in increasing order

### ISSUE THREAD

**Issue by Shalana** [asingh33/CNNGestureRecognizer#59]
Hi,
 When it loaded hdf5 file, An error message will pop out :TypeError: Indexing elements must be in increasing order. is the error related to your hdf5 file ?

**Comment by asingh33** [comment]
This could be related to the Keras layer. Possibly you are trying on some latest version of the framework.

**Comment by asingh33** [comment]
Also are you trying with Tensorflow or Theano ?
Dont forget to set "KERAS_BACKEND=tensorflow" as by default it will take Theano (which has become obsolete now)

**Comment by asingh33** [comment]
Closing this issue. As there is no further update by the filer.

**Comment by TruthZZ** [comment]
Hello,
The same error occured when I try to load hdf5 file on Windows. I've already set "KERAS_BACKEND=tensorflow". Is this error related to package versions?

**Comment by asingh33** [comment]
> Hello, The same error occured when I try to load hdf5 file on Windows. I've already set "KERAS_BACKEND=tensorflow". Is this error related to package versions?

@TruthZZ hey I dont have a windows setup at the moment to try out the code. But my suggestion would be to try retraining instead. As those trained model was done way back and now tensorflow library has updated multiple times. So I would suspect some compartibility issues with the older trained data file.

**Comment by TruthZZ** [comment]
> 

I've tried retraining the model and loading my hdf5 file. Problem solved! Thank you very much!
