### ISSUE TITLE
About the dataset used to obtain the weights provided

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [asingh33/CNNGestureRecognizer#6]
Hi 
Thanks for sharing your code and the trained model
I`ve run your code
May I ask some questions about the data set you used?
 - How many samples do you have for each gesture?
 - You created yourself or downloaded it from the internet?

Many thanks!

**Comment by asingh33** [comment]
Hey @MengXinChengXuYuan 
My answers in line.

May I ask some questions about the data set you used?
**asingh33: Yes I created my self.**

How many samples do you have for each gesture?
**asingh33: I captured 803 samples per gestures for 5 gestures (OK, PEACE, PUNCH, STOP, NOTHING). So total 4015 images. You can create as many you require, just need to edit this value in the script.**

You created yourself or downloaded it from the internet?
**asingh33: Created myself. You can actually create as well using this project. I have added the code to do so in this project. Check trackgesture.py file. While running the project you should see various options you can use. For creating your gesture you have to use 's' key to capture camera image.**

**Comment by MengXinChengXuYuan** [comment]
@asingh33 
I see, thank you
