### ISSUE TITLE
When I run gestureCNN.py,I have meet errors

### ISSUE THREAD

**Issue by liujinyan12** [asingh33/CNNGestureRecognizer#7]
When I run gestureCNN.py on windows platform, I meet the following errors:
ImportError:Failed to import pydot.You must install pydot and graphviz for 'pydotprint' to work.
After I pip install pydot,pip install graphviz.The errors are still.
How can I to do this?
Thank you .

**Comment by asingh33** [comment]
Hi there,
Sorry just now noticed this issue. Can you please tell me at which line are you getting this error msg ??

**Comment by asingh33** [comment]
Are you getting it for following line of code ?? If yes, then a quick workaround would be to comment out these two lines. Its only required to display model configuration visually. This info is anyhow being printed in the console. So not that critical requirement for the code.

**from keras.utils import plot_model
plot_model(model, to_file='new_model.png', show_shapes = True)**

**Comment by liujinyan12** [comment]
Yes ,I have solved that problem.Another error appeared again.
ljy1@ubuntu:~/CNNGestureRecognizer$ KERAS_BACKEND=theano python trackgesture.py 
Using Theano backend.
What would you like to do ?
    1- Use pretrained model for gesture recognition & layer visualization
    2- Train the model (you will require image samples for training under .\imgfolder)
    3- Visualize feature maps of different layers of trained model
    1
Will load default weight file

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 32, 198, 198)      320       
_________________________________________________________________
activation_1 (Activation)    (None, 32, 198, 198)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 196, 196)      9248      
_________________________________________________________________
activation_2 (Activation)    (None, 32, 196, 196)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 98, 98)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 32, 98, 98)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 307328)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               39338112  
_________________________________________________________________
activation_3 (Activation)    (None, 128)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 645       
_________________________________________________________________
activation_4 (Activation)    (None, 5)                 0         
=================================================================
Total params: 39,348,325
Trainable params: 39,348,325
Non-trainable params: 0
_________________________________________________________________
loading  ori_4015imgs_weights.hdf5
Traceback (most recent call last):
  File "trackgesture.py", line 300, in <module>
    Main()
  File "trackgesture.py", line 175, in Main
    mod = myNN.loadCNN(0)
  File "/home/ljy1/CNNGestureRecognizer/gestureCNN.py", line 176, in loadCNN
    model.load_weights(fname)
  File "/home/ljy1/anaconda2/lib/python2.7/site-packages/keras/models.py", line 715, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/ljy1/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ljy1/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1942)
IOError: Unable to open file (File signature not found)

And I have downloaded ori_4015imgs_weights.hdf5.

**Comment by asingh33** [comment]
Can you tell me what is the size of ori_4015imgs_weights.hdf5 file you are seeing? It should be ~150MB.

**Comment by liujinyan12** [comment]
Yes,the error was ori_4015imgs_weights.hdf5,I have downloaded another time.
Thank you!

**Comment by liujinyan12** [comment]
Hi:
 I met another problem again.

ljy1@ubuntu:~/CNNGestureRecognizer$ KERAS_BACKEND=theano python trackgesture.py 
Using Theano backend.
What would you like to do ?
    1- Use pretrained model for gesture recognition & layer visualization
    2- Train the model (you will require image samples for training under .\imgfolder)
    3- Visualize feature maps of different layers of trained model
    1
Will load default weight file
......
Total params: 39,348,325
Trainable params: 39,348,325
Non-trainable params: 0
_________________________________________________________________
loading  ori_4015imgs_weights.hdf5
ori_4015imgs_weights.hdf5
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /root/mc-x64-2.7/conda-bld/opencv-3_1482256854890/work/opencv-3.1.0/modules/highgui/src/window.cpp, line 281
Traceback (most recent call last):
  File "trackgesture.py", line 318, in <module>
    Main()
  File "trackgesture.py", line 244, in Main
    cv2.imshow('Original',frame)
cv2.error: /root/mc-x64-2.7/conda-bld/opencv-3_1482256854890/work/opencv-3.1.0/modules/highgui/src/window.cpp:281: error: (-215) size.width>0 && size.height>0 in function imshow
But,I have installed opencv,and I can use opencv to read videos and images.
ljy1@ubuntu:~/CNNGestureRecognizer$ pkg-config --modversion opencv
2.4.8
I don't know why.

**Comment by asingh33** [comment]
This error msg is actually pointing that camera input is not getting captured actually. Can you try this:
At following line in trackgesture.py file where I am setting up VideoCapture using input value as 0. Pass in value as 1 and check if it helps

## Grab camera input
cap = cv2.VideoCapture(1)

**Comment by asingh33** [comment]
Any update @liujinyan12 ??

**Comment by asingh33** [comment]
@liujinyan12  I am closing this issue. Feel free to reopen in case of any other issue you come across.
