### ISSUE TITLE
ori_4015imgs_weights.hdf5 content

### ISSUE THREAD

**Issue by hjyCoder** [asingh33/CNNGestureRecognizer#9]
Can you send this ori_4015imgs_weights.hdf5 to me?

**Comment by asingh33** [comment]
hey there,
I sure can but dont know which other way I can use to share such a large file. My Github LFS storage has run out of monthly quota for this month :( and not planning to buy additional Git datapack to unblock this. Last month I purchased but it literally got wasted as not much repo fork happend.
So if you are aware of any other better method then I can definitely share through that.

**Comment by hjyCoder** [comment]
How large the file is, Can you send me an e-mail (mydeyouxiang2@gmail.com) or you can upload to baidu Cloud disk and share the link。

**Comment by asingh33** [comment]
I have sent a google drive link for this file on your email id. Let me know if you can access it.

**Comment by hjyCoder** [comment]
Thank you. I have received your file。
